#! /bin/bash

####################################################################################################

root_path=`dirname $0`
root_path=`dirname ${root_path}`
if [ ${root_path} == '.' ]; then
  root_path=$PWD
fi

####################################################################################################

project=$1
if [ "x${project}" == "x" ]; then
  program=`basename $0`
  echo "Usage: $program path"
  exit 1
fi

####################################################################################################

files=`find ${root_path} -type f -not -wholename '*/.bzr*' -not -name "*~" -not -wholename "*/template-tools*"`

for file_ref in ${files}; do
  relative_file=${file_ref#${root_path}/}
  file=${project}/${relative_file}
  if ! [ -e ${file} ]; then
    echo "Install ${relative_file}"
    path=`dirname ${file}`
    if ! [ -e $path ]; then
      mkdir -p $path
    fi
    install ${file_ref} ${file}
  fi
done

####################################################################################################
# 
# End
# 
####################################################################################################
