#! /bin/bash
#
repository=python-project-template
#
mv .git .git-backup
git init
bzr fast-export --plain --git-branch=master | git fast-import
git remote add origin git@github.com:FabriceSalvaire/${repository}.git
git push origin # --force
# End
